name: Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: "Choose tests set"
        required: true
        default: "smoke"
        type: choice
        options:
          - smoke
          - regression
          - extended
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Clones your code into the working environment

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.5'  # Specify the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8

      - name: Run tests
        run: pytest
      
